### ISSUE TITLE
Getting rename or repackaging error.

### ISSUE THREAD

**Issue by HikmetTenis** [hibersap/hibersap#21]
Hi

I got jco version 12 and when I try to use it, it gives me "Illegal JCo archive "sapjco3-3.0.jar". It is not
allowed to rename or repackage the original archive "sapjco3.jar" error, I followed the example which is given in your web site, maven adds version to the file and jco doesnt like that, what should I do?

Thanks.

**Comment by cerker** [comment]
Hi, from JCo 3.11 on, the SAP library checks the name of its archive. You can either switch to 3.10 or handle the archive name in a special way.

Either configure Maven to exclude the version or don't handle JCo with Maven (which you usually don't want). See the discussion here: https://sourceforge.net/p/hibersap/discussion/813164/thread/52913577/
