### ISSUE TITLE
Implement Closeable interface

### ISSUE THREAD

**Issue by gregorko** [hibersap/hibersap#28]
Hello,

I think it would be nice if Session and maybe also SessionManager could implement the Closeable interface.

This would allow to use the try-with-resource statement:
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
```
try (Session s = sessionMgr.openSession()) 
{
   ....
}
```

**Comment by johnjaylward** [comment]
I don't think Session Manager should implement Closeable. It doesn't hold any actual resources, just cached configuration data that gets cleared on close(). It's technically fine if this never gets closed and the references are just released naturally by the garbage collector.
