### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by GisMarsch** [hibersap/hibersap#34]
First of all: Thank you very very very much for this great project which helps me doing things related to SAP in an easy way.

This is not an issue but more like a question:
Are there any plans doing an official release of 1.3.1 (including upload to maven repo)?
Currently I did a build of my own which is hosted in my companies maven repository having it's own release number. This is not my preferred way, but I needed the Changing parameter which was not contained in latest release.

**Comment by cerker** [comment]
Version will be 1.4.0 since the inclusion of changing parameters is a (compatible) API change.
