### ISSUE TITLE
Add the possibility to change the classpath location for hibersap.xml

### ISSUE THREAD

**Issue by cerker** [hibersap/hibersap#9]
hibersap.cfg.xml must currently be located under /META-INF in the classpath. It shall be possible for Hibersap users to specify a different path.

See forum topic: https://sourceforge.net/projects/hibersap/forums/forum/813163/topic/3705116

> Would it be possible to make the place where to hold the xml file dynamic?
> I think it would be better when the file is directly located in the source path, like hibernate.cfg.xml or the log4j.properties ...?
> 
> regards
> Markus Reich

**Comment by Linuem** [comment]
Hi @cerker , 
is there a workaround available for this? I try to use hibersap with thorntail and I dont want to bundle the config with the credentials into the uberjar. I already tried to use jca with Cuckoo but I get some strange effects.
Regards
Sebastian
